### PR TITLE
Updates Members page 

### PR DESCRIPTION
**Pull request by whi-lab**
Thanks to (@sm7gc) for pull request #2!

### CODE REVIEW

**Comment by whi-lab** [comment]
I did some minor fixing — please take a look.

**Comment by whi-lab** [comment]
Also, for members, I thought about keeping it sorted by last name — but I am ok if you prefer to have it by "seniority".

**Review by sm7gc — APPROVED** [review]
Looks good to me. I added Hee Jeong's personal website since she got that to me after the original commit. Thanks for your comments!

**Comment by sm7gc** [comment]
Also, I think ordering by "seniority" first and then alphabetically makes sense. Plus, the only difference would be that Sahiti and Hee Jeong's profiles would be swapped

**Pull request merged**
